### ISSUE TITLE
March 2017 WG meeting

### ISSUE THREAD

**Issue by mcollina** [nodejs/readable-stream#261]
Hi Folks,

When would you prefer to meet?
Here is our doodle: http://doodle.com/poll/q39ixc3s37dguecs.

We have a couple of topics:

* [x] `require('str' + 'eam')` #260 
* [x] make @lrlna part of the wg #256 
* [x] Support UInt8Array https://github.com/nodejs/node/pull/11608
* [x] Status update on the inversion of depedency between node and `readable-stream` https://github.com/nodejs/node-eps/pull/49
* [x] no `'unpipe'` event https://github.com/nodejs/node/pull/11876
* [x] localtunnel problem and update #265 

Feel free to edit this ^^.

cc @addaleax

**Comment by mcollina** [comment]
Ping @mafintosh @yoshuawuyts @lrlna

**Comment by mcollina** [comment]
I've ended the doodle for:

Friday 17 March at 16:00 GMT / 17:00 CET / {edit this with your time zone}. @calvinmetcalf please check for daylight saving time adjustments, those are the 2 terrible weeks of the year for scheduling.

**Comment by mcollina** [comment]
Watch: http://youtu.be/ALrje2bkWRo
Join: https://hangouts.google.com/hangouts/_/dl6ixy7u4bhzhl4sb735n6m32qe

**Comment by mcollina** [comment]
1. `require('str' + 'eam') is not really requiring `require('stream')` - it was not working several versions ago (v1.7.1), and nobody noticed. We are removing that at this point.
2. @lrlna is now part of the streams working group.
3. @samnewton is OK in moving that forward, @calvinmetcalf is generally in favour as long as it does not break anything, @yoshuawuyts @lrlna @mcollina take some time and figure out all the details.
4. go ahead with the ep to the CTC
5. might be semver-minor, let's check with CIGTM and our flag
6. we need to ask nodejs/build

We'll meet at the collaborator Summit in May 3-4 in Berlin.

^^ Feel free to edit it if I missed something.
